 
INCLUDE_DIRS = /home/xingzhuang/job/multiple_thread/ThreadPool/include
LIBS_PATH = /home/xingzhuang/job/multiple_thread/ThreadPool/lib
LIBS = -lthread_pool -lpthread
 

target:
	g++ -I$(INCLUDE_DIRS) -L$(LIBS_PATH) $(LIBS) test.cpp




 